export type LotteryConcept = {
  id: string;
  category: string;
  text: string;
  action: string;
  character: string;
  creative: string;
};

export const LOTTERY_CONCEPTS: LotteryConcept[] = [
  { id: "lottery-001", category: "問候", text: "早安，今天也要亮晶晶", action: "從棉被探出頭伸懶腰", character: "圓滾滾的小兔子", creative: "晨光、吐司與小星星繞在身邊" },
  { id: "lottery-002", category: "問候", text: "午安，先吃一口", action: "捧著便當開心揮手", character: "戴圍巾的小熊", creative: "便當盒冒出溫暖香氣" },
  { id: "lottery-003", category: "問候", text: "晚安，夢裡見", action: "抱著月亮造型枕頭鑽進被窩", character: "奶油色小貓", creative: "窗外有彎月與慢慢飄落的星星" },
  { id: "lottery-004", category: "問候", text: "嗨，我來報到啦", action: "從紙箱裡跳出來揮雙手", character: "調皮的小狐狸", creative: "紙箱貼著手繪報到章" },
  { id: "lottery-005", category: "問候", text: "好久不見，抱一下", action: "張開手臂飛奔靠近", character: "胖嘟嘟的小狗", creative: "兩側飄著溫暖的愛心紙片" },
  { id: "lottery-006", category: "回覆", text: "收到，交給我", action: "敬禮後抱起一疊文件", character: "認真的小企鵝", creative: "文件上蓋著圓形任務章" },
  { id: "lottery-007", category: "回覆", text: "了解，我慢慢看", action: "戴上圓眼鏡仔細讀手機", character: "安靜的小水豚", creative: "手機旁有放大鏡與小書籤" },
  { id: "lottery-008", category: "回覆", text: "沒問題，放心吧", action: "比出大拇指並露出可靠笑容", character: "穿背心的小熊貓", creative: "背後有手繪盾牌與勾勾" },
  { id: "lottery-009", category: "回覆", text: "等我一下下", action: "一手拿時鐘一手急忙穿鞋", character: "慌張的小老鼠", creative: "鞋帶飛起來形成速度線" },
  { id: "lottery-010", category: "回覆", text: "晚點回你喔", action: "揮手後轉身跑向忙碌桌面", character: "橘色小貓", creative: "桌上有便利貼與閃動的通知符號" },
  { id: "lottery-011", category: "感謝", text: "謝謝你，心裡暖暖的", action: "雙手捧著熱茶鞠躬", character: "圓臉小兔", creative: "茶杯蒸氣變成愛心雲朵" },
  { id: "lottery-012", category: "感謝", text: "甘溫啦", action: "擦著眼淚送出一顆大愛心", character: "害羞的小海豹", creative: "愛心上有手寫感謝貼紙" },
  { id: "lottery-013", category: "感謝", text: "辛苦了，給你拍拍手", action: "用力鼓掌並撒出小花", character: "穿圍裙的小狐狸", creative: "花瓣與掌聲線條環繞角色" },
  { id: "lottery-014", category: "感謝", text: "你真的很貼心", action: "抱住一個巨大的愛心枕頭", character: "奶茶色小熊", creative: "背景是柔軟格紋與暖色小燈" },
  { id: "lottery-015", category: "感謝", text: "這份心意我收到了", action: "雙手接住飄來的小禮物", character: "戴蝴蝶結的小狗", creative: "禮物盒打開灑出星星" },
  { id: "lottery-016", category: "鼓勵", text: "加油，你可以的", action: "握拳跳起來舉起加油牌", character: "活力小老虎", creative: "加油牌邊緣有彩色手繪火花" },
  { id: "lottery-017", category: "鼓勵", text: "一步一步來就好", action: "沿著小路穩穩向前走", character: "背小包的小刺蝟", creative: "路邊有小旗子與柔和太陽" },
  { id: "lottery-018", category: "鼓勵", text: "我相信你", action: "雙手比出閃亮的愛心手勢", character: "溫柔的小鹿", creative: "鹿角間掛著一串小燈泡" },
  { id: "lottery-019", category: "鼓勵", text: "太棒啦，值得慶祝", action: "拉開彩帶砲大笑歡呼", character: "穿帽子的小浣熊", creative: "彩帶寫著手繪星星與圓點" },
  { id: "lottery-020", category: "鼓勵", text: "今天也完成一件事", action: "在清單上打勾後開心轉圈", character: "小小的黃色鴨子", creative: "完成清單像一本可愛手帳" },
  { id: "lottery-021", category: "情緒", text: "哈哈哈笑到停不下來", action: "捧腹大笑滾到地上", character: "圓滾滾的水豚", creative: "笑聲字樣變成跳動的小圓球" },
  { id: "lottery-022", category: "情緒", text: "真的假的啦", action: "瞪大眼睛拿放大鏡靠近看", character: "驚訝的小貓", creative: "眼睛旁浮著三個問號" },
  { id: "lottery-023", category: "情緒", text: "我先震驚一下", action: "雙手摀嘴停在原地", character: "小白兔", creative: "背景出現彈跳的驚嘆號" },
  { id: "lottery-024", category: "情緒", text: "有點尷尬但先微笑", action: "僵硬微笑並揮小手", character: "戴帽子的狗狗", creative: "額頭有一滴手繪冷汗" },
  { id: "lottery-025", category: "情緒", text: "我暈，資訊好多", action: "抱著資料堆慢慢倒下", character: "小灰鼠", creative: "文件像瀑布一樣從上方落下" },
  { id: "lottery-026", category: "生活", text: "吃飽沒？一起吃", action: "端著兩碗熱呼呼的麵招手", character: "圍兜兜的小熊", creative: "麵碗旁有小菜與蒸氣線" },
  { id: "lottery-027", category: "生活", text: "我到了，在門口喔", action: "撐傘站在門口揮手", character: "小狐狸", creative: "門牌與雨滴用暖色手繪線條呈現" },
  { id: "lottery-028", category: "生活", text: "在路上，快到了", action: "背著小包向前小跑步", character: "小企鵝", creative: "腳下有兩朵速度雲" },
  { id: "lottery-029", category: "生活", text: "等我一下，我找不到鑰匙", action: "趴在地上翻找一大串鑰匙", character: "慌張的小貓", creative: "鑰匙散落成一圈迷你星星" },
  { id: "lottery-030", category: "生活", text: "今天想穿得可愛一點", action: "在鏡子前比出俏皮姿勢", character: "穿吊帶裙的小兔", creative: "鏡子旁有蝴蝶結與小花貼紙" },
  { id: "lottery-031", category: "天氣", text: "今天好冷，借我抱一下", action: "裹著毛毯伸出雙手", character: "小海豹", creative: "周圍飄著雪花與熱可可蒸氣" },
  { id: "lottery-032", category: "天氣", text: "熱到融化了", action: "趴在冰塊上用小扇子搧風", character: "橘色小貓", creative: "冰塊旁有檸檬與涼感水滴" },
  { id: "lottery-033", category: "天氣", text: "下雨天也要好心情", action: "穿雨鞋踩水坑開心跳起", character: "小黃鴨", creative: "透明雨傘上畫著彩虹" },
  { id: "lottery-034", category: "天氣", text: "風好大，我先抓緊", action: "抱住路牌被風吹成斜斜的姿勢", character: "小刺蝟", creative: "葉片與帽子在空中飛舞" },
  { id: "lottery-035", category: "天氣", text: "曬太陽充電中", action: "躺在向日葵旁伸展四肢", character: "奶油色小狗", creative: "陽光畫成溫暖放射線" },
  { id: "lottery-036", category: "工作", text: "開會中，稍後回覆", action: "坐在小會議桌前舉起暫停牌", character: "戴眼鏡的小熊", creative: "桌面有咖啡、筆記與小麥克風" },
  { id: "lottery-037", category: "工作", text: "馬上處理，交給我", action: "抱著檔案快步衝刺", character: "小狐狸", creative: "檔案夾上有醒目的完成章" },
  { id: "lottery-038", category: "工作", text: "事情好多但我不慌", action: "同時拿三支筆在便利貼上排優先順序", character: "小水豚", creative: "便利貼整齊排成彩色階梯" },
  { id: "lottery-039", category: "工作", text: "辛苦一天，收工啦", action: "關上筆電伸懶腰歡呼", character: "小貓", creative: "窗外夕陽與下班小旗子" },
  { id: "lottery-040", category: "工作", text: "先喝口咖啡再戰", action: "雙手抱著超大馬克杯", character: "小熊", creative: "咖啡蒸氣形成小小閃電" },
  { id: "lottery-041", category: "休息", text: "我需要五分鐘發呆", action: "坐在軟墊上看著窗外放空", character: "小鹿", creative: "窗邊有盆栽與慢慢飄的雲" },
  { id: "lottery-042", category: "休息", text: "今天只想耍廢", action: "躺在沙發上抱著遙控器", character: "胖胖的小狗", creative: "零食、抱枕與小毯子散在身旁" },
  { id: "lottery-043", category: "休息", text: "補眠一下，等等見", action: "戴睡帽鑽進一朵雲形枕頭", character: "小兔子", creative: "鬧鐘被放在遠遠的床頭" },
  { id: "lottery-044", category: "休息", text: "我正在慢慢恢復能量", action: "坐在充電座旁閉眼冥想", character: "小企鵝", creative: "頭頂浮著一顆溫柔電池圖示" },
  { id: "lottery-045", category: "休息", text: "安靜陪我就好", action: "和一杯熱茶並肩坐著", character: "小貓", creative: "背景留白、只有柔和桌燈" },
  { id: "lottery-046", category: "安慰", text: "別難過，我在這裡", action: "遞出手帕並輕輕拍肩", character: "小熊", creative: "手帕上繡著小太陽" },
  { id: "lottery-047", category: "安慰", text: "抱一下就會好一點", action: "張開手臂送出大擁抱", character: "小海豹", creative: "擁抱外圍有柔軟的雲朵" },
  { id: "lottery-048", category: "安慰", text: "慢慢來，你不用一個人", action: "陪著對方坐在長椅上", character: "小鹿", creative: "長椅旁有兩杯溫熱飲料" },
  { id: "lottery-049", category: "安慰", text: "今天已經很努力了", action: "替對方披上一條毯子", character: "小狐狸", creative: "毯子上有手繪星星與月亮" },
  { id: "lottery-050", category: "安慰", text: "先休息，明天再想", action: "把煩惱放進小盒子蓋起來", character: "小兔子", creative: "盒子變成一顆安靜的月亮" },
  { id: "lottery-051", category: "戀愛", text: "想你了，給你一顆心", action: "抱著愛心向前蹦跳", character: "橘色小貓", creative: "愛心裡藏著兩人的小剪影" },
  { id: "lottery-052", category: "戀愛", text: "陪我吃一頓飯嘛", action: "拉著對方的袖子撒嬌", character: "小兔子", creative: "餐桌上有兩副可愛餐具" },
  { id: "lottery-053", category: "戀愛", text: "見到你就很幸福", action: "捧著臉頰開心轉圈", character: "小熊", creative: "背景有粉色泡泡與小花" },
  { id: "lottery-054", category: "戀愛", text: "記得想我一下", action: "用手指戳著自己的臉比愛心", character: "小狐狸", creative: "旁邊有一張寫著想念的便條" },
  { id: "lottery-055", category: "戀愛", text: "晚點見，抱緊處理", action: "抱著一大束花小跑步", character: "小狗", creative: "花束上綁著手寫蝴蝶結" },
  { id: "lottery-056", category: "可愛", text: "啾咪一下嘛", action: "歪頭眨眼比出小愛心", character: "小兔子", creative: "臉旁有兩顆閃亮腮紅" },
  { id: "lottery-057", category: "可愛", text: "今天也萌萌的", action: "戴上大耳朵帽子轉一圈", character: "小熊貓", creative: "帽子上有小鈴鐺與彩帶" },
  { id: "lottery-058", category: "可愛", text: "可以原諒我嗎", action: "雙手合十並露出水汪汪眼神", character: "小狗", creative: "頭上飄著一朵小小烏雲" },
  { id: "lottery-059", category: "可愛", text: "就這樣說定囉", action: "伸出小指打勾勾", character: "小貓", creative: "小指旁有金色星星與印章" },
  { id: "lottery-060", category: "可愛", text: "一起玩嘛", action: "抱著彩色玩具向前招手", character: "小海豹", creative: "玩具是圓圓的彩虹積木" },
  { id: "lottery-061", category: "搞笑", text: "啊不就很會", action: "雙手抱胸挑眉吐槽", character: "戴墨鏡的水豚", creative: "背後有誇張閃電與小喇叭" },
  { id: "lottery-062", category: "搞笑", text: "先讓專業的來", action: "推開簾子自信走上小舞台", character: "穿斗篷的小狐狸", creative: "舞台上只有一盞聚光燈" },
  { id: "lottery-063", category: "搞笑", text: "我只是路過一下", action: "踮腳從畫面邊緣偷偷經過", character: "小老鼠", creative: "身後拖著一條過場速度線" },
  { id: "lottery-064", category: "搞笑", text: "這劇情我沒看懂", action: "抱著爆米花歪頭看大螢幕", character: "小熊", creative: "螢幕上是旋轉的問號" },
  { id: "lottery-065", category: "搞笑", text: "先笑再說", action: "戴著派對眼鏡噴出彩帶", character: "小企鵝", creative: "彩帶形成一個大大的笑臉" },
  { id: "lottery-066", category: "自嘲", text: "我就先這樣", action: "坐進紙箱只露出兩隻眼睛", character: "小貓", creative: "紙箱寫著暫時離線" },
  { id: "lottery-067", category: "自嘲", text: "腦袋需要重新開機", action: "按下頭頂的重開按鈕", character: "小機器人兔", creative: "頭頂跑出旋轉小齒輪" },
  { id: "lottery-068", category: "自嘲", text: "今天的我有點迷路", action: "拿著地圖原地轉圈", character: "小刺蝟", creative: "地圖被畫滿可愛箭頭" },
  { id: "lottery-069", category: "自嘲", text: "我與成功只差一張床", action: "伸手想拿獎杯卻躺回枕頭", character: "小熊", creative: "床邊有一座迷你獎杯" },
  { id: "lottery-070", category: "自嘲", text: "我先假裝很懂", action: "戴眼鏡點頭卻把書拿反", character: "小狐狸", creative: "書頁上畫著顛倒的小星星" },
  { id: "lottery-071", category: "美食", text: "開飯啦，先吃再說", action: "舉起湯匙歡呼", character: "戴圍兜的小熊", creative: "桌上有熱湯與繽紛小菜" },
  { id: "lottery-072", category: "美食", text: "這口我先幫你試試", action: "拿著小叉子偷吃一口", character: "小貓", creative: "餐盤旁有偷吃成功的小印章" },
  { id: "lottery-073", category: "美食", text: "甜點是另一個胃", action: "抱住高高的蛋糕塔", character: "小兔子", creative: "蛋糕上有小小水果旗" },
  { id: "lottery-074", category: "美食", text: "今天喝水了嗎", action: "舉起水壺認真提醒", character: "小狗", creative: "水壺上畫著清爽葉片" },
  { id: "lottery-075", category: "美食", text: "再一口就好", action: "把最後一顆飯糰藏到身後", character: "小老鼠", creative: "飯糰海苔上有笑臉" },
  { id: "lottery-076", category: "節日", text: "今天值得慶祝", action: "拉起彩旗並跳舞", character: "小熊貓", creative: "彩旗寫著今天真好" },
  { id: "lottery-077", category: "節日", text: "生日快樂，願望成真", action: "端著插滿蠟燭的蛋糕", character: "小狐狸", creative: "蠟燭火光變成小星球" },
  { id: "lottery-078", category: "節日", text: "週末愉快，放空一下", action: "戴草帽躺在野餐墊上", character: "小水豚", creative: "野餐籃與雲朵組成悠閒構圖" },
  { id: "lottery-079", category: "節日", text: "新的開始，慢慢發光", action: "把小旗子插在新芽旁", character: "小鹿", creative: "背景是柔和晨光與新葉" },
  { id: "lottery-080", category: "節日", text: "把好心情分你一半", action: "把一顆發光氣球遞出去", character: "小海豹", creative: "氣球中有兩半拼起來的笑臉" },
  { id: "lottery-081", category: "提醒", text: "記得帶傘喔", action: "把透明雨傘遞向畫面外", character: "小狗", creative: "雨傘上有一顆溫柔小太陽" },
  { id: "lottery-082", category: "提醒", text: "小心腳下，慢慢走", action: "舉著小心地滑牌子", character: "小企鵝", creative: "腳邊有兩個可愛小水坑" },
  { id: "lottery-083", category: "提醒", text: "記得休息眼睛", action: "把眼鏡拿下並做眼睛伸展操", character: "小熊", creative: "眼睛旁有柔和星星與按摩線" },
  { id: "lottery-084", category: "提醒", text: "不要忘記帶充電線", action: "像偵探一樣舉起充電線尋找", character: "小狐狸", creative: "充電線繞成問號形狀" },
  { id: "lottery-085", category: "提醒", text: "深呼吸，再出發", action: "閉眼吸氣後向前踏一步", character: "小兔子", creative: "呼吸線條化成一片小葉子" },
  { id: "lottery-086", category: "期待", text: "我已經開始期待了", action: "抱著日曆把日期圈起來", character: "小貓", creative: "日曆旁有倒數小旗子" },
  { id: "lottery-087", category: "期待", text: "好消息正在路上", action: "站在路邊迎接一台小郵車", character: "小熊", creative: "郵車拖著一條閃亮彩帶" },
  { id: "lottery-088", category: "期待", text: "等等見，我先準備好", action: "快速整理小背包", character: "小狗", creative: "背包裡露出帽子與小相機" },
  { id: "lottery-089", category: "期待", text: "這次一定會很開心", action: "雙手捧著一顆期待的星星", character: "小鹿", creative: "星星周圍有小小的預告紙片" },
  { id: "lottery-090", category: "期待", text: "準備出發去收集回憶", action: "背著相機踏上彩色小路", character: "小企鵝", creative: "路邊有手繪相片框與小花" },
  { id: "lottery-091", category: "創作", text: "靈感請降落", action: "伸手接住從天上飄下的鉛筆", character: "戴貝雷帽的小兔", creative: "靈感變成彩色紙片與小星球" },
  { id: "lottery-092", category: "創作", text: "先畫一個小小的開始", action: "在空白紙上畫出第一條線", character: "小狐狸", creative: "線條變成一扇通往想像的門" },
  { id: "lottery-093", category: "創作", text: "這個點子我喜歡", action: "把發光燈泡抱在懷裡", character: "小水豚", creative: "燈泡內有迷你彩色房間" },
  { id: "lottery-094", category: "創作", text: "改一點點就更好了", action: "拿橡皮擦仔細修稿", character: "小熊", creative: "紙上有可愛的修改符號與星星" },
  { id: "lottery-095", category: "創作", text: "我的風格，我作主", action: "站在小畫布前自信比讚", character: "小貓", creative: "畫布上是抽象暖色圓點" },
  { id: "lottery-096", category: "療癒", text: "送你一點柔軟的光", action: "捧著小夜燈慢慢靠近", character: "小海豹", creative: "夜燈周圍有溫柔的金色光暈" },
  { id: "lottery-097", category: "療癒", text: "今天也值得被好好對待", action: "替自己戴上一朵小花", character: "小兔子", creative: "背景是米白紙張與淡淡花瓣" },
  { id: "lottery-098", category: "療癒", text: "把煩惱放下來一點", action: "把沉重背包放到地上", character: "小熊", creative: "背包裡飄出幾朵輕盈雲朵" },
  { id: "lottery-099", category: "療癒", text: "小小幸福正在發生", action: "蹲下觀察一朵剛開的小花", character: "小鹿", creative: "花朵旁有微小閃光與圓點" },
  { id: "lottery-100", category: "療癒", text: "今天先對自己溫柔", action: "抱住自己並蓋上柔軟小毯子", character: "小貓", creative: "毯子上有月亮與手繪葉片" },
  { id: "lottery-101", category: "社交", text: "要不要一起走走", action: "背著小包回頭揮手邀請", character: "小狐狸", creative: "前方是一條有彩旗的小路" },
  { id: "lottery-102", category: "社交", text: "我也想加入", action: "從畫面邊緣舉手探頭", character: "小企鵝", creative: "旁邊有手繪加入章與小圓點" },
  { id: "lottery-103", category: "社交", text: "下次換我請客", action: "拿出小錢包豪氣比讚", character: "小熊", creative: "桌上有兩杯飲料與小票券" },
  { id: "lottery-104", category: "社交", text: "今天聊得很開心", action: "抱著聊天泡泡滿足微笑", character: "小水豚", creative: "對話泡泡飄成彩色小雲" },
  { id: "lottery-105", category: "社交", text: "有空再約喔", action: "揮手走進夕陽小巷", character: "小狗", creative: "巷口掛著下一次見的小旗子" },
];

export const LOTTERY_CONCEPT_COUNT = LOTTERY_CONCEPTS.length;

export function pickLotteryConcept(recentIds: string[] = [], random = Math.random): LotteryConcept {
  const fresh = LOTTERY_CONCEPTS.filter((concept) => !recentIds.includes(concept.id));
  const pool = fresh.length ? fresh : LOTTERY_CONCEPTS;
  return pool[Math.floor(random() * pool.length)] ?? LOTTERY_CONCEPTS[0]!;
}
