import { Download, Eye, ImagePlus, MessageCircle, ShieldCheck, Sparkles } from "lucide-react";
import { PREVIEW_DEMO } from "@/lib/previewDemo";

function DemoSticker({ number, text, pose, status }: typeof PREVIEW_DEMO.stickers[number]) {
  return <article className="rounded-2xl border border-[#e7d2bb] bg-white p-3 shadow-sm"><div className="relative flex h-28 items-center justify-center overflow-hidden rounded-xl bg-[#fff6e9]"><span className="absolute left-2 top-2 text-xs font-bold text-[#a8673f]">#{String(number).padStart(2, "0")}</span><div className="relative h-16 w-16 rounded-[45%] bg-[#fffdf8] shadow-[inset_0_0_0_2px_#d9b28b]"><span className="absolute -left-1 -top-7 h-10 w-6 -rotate-12 rounded-t-full bg-[#fffdf8] shadow-[inset_0_0_0_2px_#d9b28b]" /><span className="absolute -right-1 -top-7 h-10 w-6 rotate-12 rounded-t-full bg-[#fffdf8] shadow-[inset_0_0_0_2px_#d9b28b]" /><span className="absolute left-5 top-7 h-1.5 w-1.5 rounded-full bg-[#68483a]" /><span className="absolute right-5 top-7 h-1.5 w-1.5 rounded-full bg-[#68483a]" /><span className="absolute left-7 top-11 h-1.5 w-2 rounded-full bg-[#db9d92]" /></div><span className="absolute bottom-2 right-2 rounded-full bg-white px-2 py-1 text-xs font-semibold text-[#a64b32]">{text}</span></div><div className="mt-2 flex items-center justify-between gap-2"><div><b className="text-sm text-[#442d22]">{text}</b><small className="block text-xs text-[#806354]">{pose}</small></div><span className="text-[11px] text-[#5d8460]">{status}</span></div></article>;
}

export default function Preview({ inspection = false }: { inspection?: boolean }) {
  const screenTitle = inspection ? "UI INSPECTION / DESKTOP + MOBILE" : "DEMO / PREVIEW";
  return <main className="min-h-screen bg-[#fff9f0] px-4 py-5 text-[#442d22] sm:px-8"><div className="mx-auto max-w-6xl"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-[#ead6c1] pb-4"><div><div className="text-xs font-bold tracking-[0.15em] text-[#a64b32]">{screenTitle}</div><h1 className="mt-1 text-2xl font-semibold">Sticker Muse 公開唯讀展示</h1><p className="mt-1 max-w-2xl text-sm text-[#806354]">此頁只使用固定測試資料，不會登入、不讀取專案、不上傳檔案，也不會呼叫 AI 或下載你的作品。</p></div><a href="/" className="rounded-full border border-[#d9bfa7] px-4 py-2 text-sm font-medium text-[#8b3f2d]">回到工作室</a></header>
  <section className="mt-5 grid gap-4 lg:grid-cols-[1.15fr_0.85fr]"><div className="rounded-2xl border border-[#ead6c1] bg-white p-4 shadow-sm"><div className="flex items-center gap-2"><MessageCircle size={18} className="text-[#a64b32]" /><b>Chat-first 創作對話</b><span className="ml-auto rounded-full bg-[#fff0df] px-2 py-1 text-xs text-[#a64b32]">DEMO</span></div><div className="mt-4 space-y-3"><div className="max-w-[85%] rounded-2xl rounded-tl-sm bg-[#f8eee0] p-3 text-sm">{PREVIEW_DEMO.prompt}</div><div className="ml-auto max-w-[90%] rounded-2xl rounded-tr-sm bg-[#fff7ed] p-3 text-sm">可以！我會分析角色、規劃 8 張，並逐張生成與檢查。你之後可直接說「第 3 張改成生氣」。</div><div className="rounded-xl border border-dashed border-[#d9bfa7] p-3 text-sm"><ImagePlus size={16} className="mr-2 inline text-[#a64b32]" />上傳狀態：角色照片 1 張 · Character Reference</div></div><div className="mt-4 flex items-center gap-2 rounded-xl border border-[#ead6c1] bg-[#fffdf8] p-2 text-sm text-[#806354]"><span className="flex-1">輸入訊息…（展示模式不會送出）</span><button disabled className="rounded-lg bg-[#b56c37] px-3 py-1 text-white opacity-60">送出</button></div></div>
  <aside className="rounded-2xl border border-[#ead6c1] bg-white p-4 shadow-sm"><div className="flex items-center gap-2"><Sparkles size={18} className="text-[#a64b32]" /><b>Agent 工作進度</b></div><ol className="mt-4 space-y-3">{PREVIEW_DEMO.stages.map((stage, index) => <li key={stage} className="flex items-center gap-3"><span className={`flex h-6 w-6 items-center justify-center rounded-full text-xs font-bold ${index < 6 ? "bg-[#dcebd8] text-[#477151]" : "bg-[#fff0df] text-[#a64b32]"}`}>{index < 6 ? "✓" : "7"}</span><span className="text-sm">{stage}</span><small className="ml-auto text-xs text-[#806354]">{index < 6 ? "完成" : "已保存"}</small></li>)}</ol><div className="mt-4 rounded-xl bg-[#f8eee0] p-3 text-xs text-[#806354]"><ShieldCheck size={14} className="mr-1 inline text-[#5d8460]" />Preview 不包含 API key、私有 asset URL 或任何個人資料。</div></aside></section>
  <section className="mt-5 rounded-2xl border border-[#ead6c1] bg-[#fffdf8] p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><div className="text-xs font-bold tracking-[0.12em] text-[#a64b32]">COMPLETED STICKER GRID</div><h2 className="text-lg font-semibold">生成、修改、版本與品質狀態</h2></div><span className="rounded-full bg-[#eaf3e8] px-3 py-1 text-sm text-[#52735a]">8 / 8 · LINE Preflight 已通過</span></div><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{PREVIEW_DEMO.stickers.map((sticker) => <DemoSticker key={sticker.number} {...sticker} />)}</div></section>
  <section className="mt-5 grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-[#ead6c1] bg-white p-4"><Eye size={18} className="text-[#a64b32]" /><b className="ml-2">修改狀態</b><p className="mt-2 text-sm text-[#806354]">第 3 張：V1 →「眼睛再大一點」→ V2，僅影響目標 job。</p></div><div className="rounded-2xl border border-[#ead6c1] bg-white p-4"><ShieldCheck size={18} className="text-[#a64b32]" /><b className="ml-2">Quality Check</b><p className="mt-2 text-sm text-[#806354]">角色、構圖、肢體、文字與 LINE 檔案預檢已分層呈現。</p></div><div className="rounded-2xl border border-[#ead6c1] bg-white p-4"><Download size={18} className="text-[#a64b32]" /><b className="ml-2">Export 狀態</b><p className="mt-2 text-sm text-[#806354]">PNG、ZIP、透明背景、尺寸、檔案大小與命名檢查展示。</p></div></section>
  {inspection && <section className="mt-5 rounded-2xl border border-[#a8673f] bg-[#fff5e8] p-4 text-sm"><b>Inspection Checklist</b><ul className="mt-2 grid gap-1 text-[#806354] sm:grid-cols-2"><li>✓ 桌面 chat-first layout</li><li>✓ 390 px mobile stacked layout</li><li>✓ 上傳、AI 回覆、進度、結果網格</li><li>✓ 修改、版本、品質、匯出 UI</li></ul></section>}</div></main>;
}
