import { Check, Download, FileArchive, History, ImagePlus, Loader2, Paperclip, Play, RefreshCw, Send, Sparkles, WandSparkles, X } from "lucide-react";
import { type ReactNode, type RefObject } from "react";
import { Link } from "wouter";

export type SharedAttachment = { id: string | number; name: string; mimeType?: string; url?: string; preview?: string; role?: string };
export type SharedHealth = { label: string; status: "healthy" | "checking" | "quota_exhausted" | "disabled" };

export function StudioTopbar({ projectName, onCopyProject, demo = false }: { projectName?: string; onCopyProject?: () => void; demo?: boolean }) {
  return <header className="chat-topbar"><div className="chat-brand"><span className="brand-spark"><Sparkles size={17} /></span><div><strong>貼圖大亨</strong><small>{demo ? "AI Inspection Preview" : "AI LINE 貼圖工作室"}</small></div></div><div className="topbar-actions">{demo ? <><span className="preview-mode-badge">DEMO / PREVIEW</span><Link href="/preview/inspection" className="preview-link">Inspection</Link></> : <><Link href="/preview" className="preview-link">Preview</Link>{projectName && <div className="project-chip"><span>專案</span><strong>{projectName}</strong><button onClick={onCopyProject}>專案代碼</button></div>}</>}</div></header>;
}

export function StudioMessage({ role, children, attachments = [] }: { role: "user" | "assistant"; children: ReactNode; attachments?: SharedAttachment[] }) {
  return <article className={`chat-message ${role}`}><div className="message-avatar">{role === "assistant" ? <Sparkles size={15} /> : "你"}</div><div className="message-content">{children}{attachments.length > 0 && <div className="message-attachments">{attachments.map((attachment) => attachment.preview || attachment.url ? <img key={attachment.id} src={attachment.preview ?? attachment.url} alt={attachment.name} /> : <span key={attachment.id}><Paperclip size={13} />{attachment.name}</span>)}</div>}</div></article>;
}

export function StudioAgentWorkspace({ title, copy, health, onAttach, onPlan, onPackEdit, onResume, events = [], results = [], onResultEdit, onResultDownload, disabled = false, demo = false }: { title: string; copy: ReactNode; health: SharedHealth[]; onAttach?: () => void; onPlan: (count: number) => void; onPackEdit?: () => void; onResume?: () => void; events?: Array<{ id: string | number; message: string; status: string }>; results?: Array<{ id: string | number; url: string; position: number; phrase: string }>; onResultEdit?: (position: number) => void; onResultDownload?: (position: number) => void; disabled?: boolean; demo?: boolean }) {
  return <section className="agent-inline-card" aria-label="AI 製作狀態與快捷操作"><div className="agent-card-head"><div><span className="eyebrow">AGENT WORKSPACE</span><strong>{title}</strong></div><WandSparkles size={18} /></div><div className="provider-health" aria-label="圖像 Provider 狀態">{health.map((item) => <span className={item.status} key={item.label}>{item.label} · {item.status === "healthy" ? "可用" : item.status === "quota_exhausted" ? "額度暫停" : item.status === "disabled" ? "未設定" : "檢查中"}</span>)}</div>{events.length > 0 ? <div className="agent-events">{events.map((event) => <div className={`agent-event ${event.status}`} key={event.id}><i /><span>{event.message}</span></div>)}</div> : <div className="agent-card-copy">{copy}</div>}{results.length > 0 && <div className="agent-result-strip">{results.map((result) => <article key={result.id}><img src={result.url} alt={`第 ${result.position} 張 ${result.phrase}`} /><div><strong>第 {result.position} 張 · {result.phrase}</strong><span>{onResultEdit && <button onClick={() => onResultEdit(result.position)} disabled={disabled}>修改</button>}{onResultDownload && <button onClick={() => onResultDownload(result.position)} disabled={disabled}>下載</button>}</span></div></article>)}</div>}<div className="agent-quick-actions">{onAttach && <button onClick={onAttach} disabled={disabled}><ImagePlus size={14} />{demo ? "上傳角色（示範）" : "上傳角色照"}</button>}{[8, 16, 24, 32, 40].map((count) => <button key={count} onClick={() => onPlan(count)} disabled={disabled}><Sparkles size={14} />{count} 張</button>)}{onPackEdit && <button onClick={onPackEdit} disabled={disabled}><WandSparkles size={14} />整套修改</button>}{onResume && <button onClick={onResume} disabled={disabled}><Play size={14} />繼續製作</button>}</div></section>;
}

export function StudioComposer({ value, onChange, onSend, onAttach, attachments = [], onRemove, inputRef, disabled = false, demo = false, allowEmpty = false, ariaLabel }: { value: string; onChange: (value: string) => void; onSend: () => void; onAttach?: () => void; attachments?: SharedAttachment[]; onRemove?: (id: SharedAttachment["id"]) => void; inputRef?: RefObject<HTMLTextAreaElement | null>; disabled?: boolean; demo?: boolean; allowEmpty?: boolean; ariaLabel?: string }) {
  return <div className="composer-wrap"><div className="queued-files">{attachments.map((attachment) => <div className="queued-file" key={attachment.id}>{attachment.preview ? <img src={attachment.preview} alt="" /> : <Paperclip size={15} />}<span>{attachment.name}</span>{attachment.role && <small>{attachment.role}</small>}{onRemove && <button aria-label={`移除 ${attachment.name}`} onClick={() => onRemove(attachment.id)}><X size={14} /></button>}</div>)}</div><div className="composer">{onAttach && <button type="button" className="attach-button" aria-label="上傳圖片或檔案" onClick={onAttach}><ImagePlus size={19} /></button>}<textarea aria-label={ariaLabel} ref={inputRef} value={value} onChange={(event) => onChange(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); onSend(); } }} placeholder="例如：幫我把這隻貓做成 8 張可愛的 LINE 貼圖，使用繁體中文。" rows={1} disabled={disabled} /><button className="send-button" onClick={onSend} disabled={disabled || (!allowEmpty && !value.trim())}>{disabled ? <Loader2 className="spin" size={18} /> : <Send size={18} />}</button></div><small>{demo ? "唯讀示範：按鈕只改變本頁固定流程，不上傳、不連線，也不建立專案。" : "可上傳多張角色照片；HEIC 會在手機／瀏覽器端轉檔。輸入「用這張做姿勢參考」或「後續全部照這個風格」即可調整 Anchor。"}</small></div>;
}

export function StudioPreflight({ total, completed, transparent, safeMargin, exportReady, demo = false }: { total: number; completed: number; transparent: number; safeMargin: number; exportReady: boolean; demo?: boolean }) {
  return <section className="main-preflight" aria-label="LINE Preflight"><div><span className="eyebrow">LINE PREFLIGHT</span><strong>{exportReady ? "可建立 LINE ZIP" : `${completed} / ${total} 張可輸出`}</strong></div><p><Check size={13} />PNG 370 × 320（輸出時）</p><p className={transparent === completed ? "passed" : "pending"}><Check size={13} />透明背景 {transparent} / {completed}</p><p className={safeMargin === completed ? "passed" : "pending"}><Check size={13} />10 px 安全邊距 {safeMargin} / {completed}</p><p><Check size={13} />繁中以伺服器 SVG 後製</p>{demo && <p><Check size={13} />Demo 輸出僅展示，不建立檔案</p>}</section>;
}

export function StudioStickerTask({ position, phrase, emotion, imageUrl, status, router, quality, versionLabel = "V1", onEdit, onRetry, onDownload, onVersion, versionRail, demo = false }: { position: number; phrase: string; emotion: string; imageUrl?: string; status: string; router: string; quality: string; versionLabel?: string; onEdit?: () => void; onRetry?: () => void; onDownload?: () => void; onVersion?: () => void; versionRail?: ReactNode; demo?: boolean }) {
  const label = status === "completed" || status === "ready" ? "已完成" : status === "paused_quota" ? "額度暫停" : status === "generating" ? "正在生成" : status === "failed" ? "需要重試" : "等待中";
  return <article className="sticker-task"><div className="task-image">{imageUrl ? <img src={imageUrl} alt={`第 ${position} 張 ${phrase}`} /> : <span>{position}</span>}<em className={`task-status ${status}`}>{label}</em></div><div className="task-meta"><small>第 {position} 張 · {emotion}</small><strong>{phrase}</strong><span className="task-router">{router} · {quality}</span><div className="task-actions">{imageUrl && <button onClick={onDownload} aria-label={`匯出第 ${position} 張 LINE PNG`}><Download size={14} /></button>}<button onClick={onEdit} disabled={!imageUrl}>告訴 AI 修改</button><button onClick={onVersion}><History size={13} />{versionLabel}</button>{["failed", "error", "paused_quota"].includes(status) && <button onClick={onRetry}><RefreshCw size={13} />{demo ? "重試" : "重試"}</button>}</div>{versionRail}</div></article>;
}

export function StudioDemoExport({ onPng, onZip }: { onPng: () => void; onZip: () => void }) {
  return <div className="panel-buttons"><button className="line-export-button" onClick={onZip}><FileArchive size={14} />LINE ZIP</button><button className="continue-button" onClick={onPng}><Download size={14} />PNG</button></div>;
}
