import { chromium } from "playwright";

const url = process.env.STICKER_PREVIEW_URL || "https://3000-is7gr11wsyrrjw4z7n36n-c7d3bcf6.sg1.manus.computer/";
const imagePath = "/home/ubuntu/upload/1787063087666.jpg";
const browser = await chromium.launch({ headless: true, executablePath: "/usr/bin/chromium", args: ["--no-sandbox", "--disable-dev-shm-usage"] });
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true });
await page.goto(url, { waitUntil: "networkidle", timeout: 30000 });
const attachmentInput = page.locator("#sticker-chat-attachments");
await attachmentInput.setInputFiles(imagePath);
const attachmentCount = await page.locator('[aria-label="聊天附件"] > span').count();
const thumbnailCount = await page.locator('img[alt^="附件預覽"]').count();
const textarea = page.locator('textarea[placeholder*="我想做一組兔子日常貼圖"]');
await textarea.fill("我沒有想法，幫我抽一張靈感");
await textarea.press("Enter");
await page.waitForTimeout(12000);
const lotteryReply = await page.locator("text=/抽到|抽一組|靈感/").count();
const attachmentAfterChat = await page.locator('[aria-label="聊天附件"] > span').count();
const resultShelf = await page.locator(".sticker-card").count();
const chatText = await page.locator(".sticker-chat-card").innerText();
await page.screenshot({ path: "/home/ubuntu/screenshots/mobile-chat-attachments-revision.png", fullPage: true });
console.log(JSON.stringify({ viewport: page.viewportSize(), attachmentCount, thumbnailCount, attachmentAfterChat, lotteryReply, resultShelf, chatText: chatText.slice(-500) }));
await browser.close();
if (attachmentCount !== 1 || thumbnailCount !== 1 || attachmentAfterChat !== 1 || lotteryReply < 1 || !/AI 圖片服務|抽到|尚未生成圖片/.test(chatText)) process.exit(1);
